break out steps

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,5 +1,4 @@
----
-format_version: '13'
+format_version: "13"
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: other
 workflows:
@@ -8,7 +7,7 @@ workflows:
     - script@1:
         title: Install GHA Runner
         inputs:
-        - content: |-
+        - content: |
             #!/usr/bin/env bash
             # fail if any commands fails
             set -e
@@ -22,10 +21,22 @@ workflows:
             echo "67d3b4dd6f1eec8ec43dda12c189cff68ec3ba1dfa054791cb446ddcfb39d2aa  actions-runner-osx-arm64-2.322.0.tar.gz" | shasum -a 256 -c
             tar xzf ./actions-runner-osx-arm64-2.322.0.tar.gz
             ./config.sh --url https://github.com/benbitrise/cowsay --token $GHA_TOKEN --ephemeral --labels bitrise
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
             ./run.sh
+        title: Run GHA
     triggers:
       push:
-      - branch: "*"
+      - branch: '*'
 meta:
   bitrise.io:
     stack: osx-xcode-16.2.x
